name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-avr avr-libc libwxgtk3.0-gtk3-dev libcurl4-gnutls-dev libusb-dev
    - name: make
      run: make -C src
    - name: make usbprog
      run: |
        cd usbprog/usbprog-0.1.8
        ./configure
        make maintainer-clean
        ./bootstrap
        ./configure
        make -j
    - name: Artifacts upload
      uses: actions/upload-artifact@v2
      with:
        name: Binary-for-atmega32-and-usbprog
        path: |
          src/main.hex
          usbprog/*/gui/.libs/usbprog-gui
          usbprog/*/usbprog/.libs/libusbprog.*
